Lesson 04
CryptoSFor/gocourse pull request #6
Opened 2021-07-16 12:15 UTC by CryptoSFor

lesson_04

2021-07-16 15:25 UTC, dimonl approved these changes

2021-07-17 06:29 UTC, rat6666 requested changes

2021-07-17 06:29 UTC, rat6666 commented on lesson_04/main.go
> +}
Why is everything in one file?It was just an example. Please, move interface and entities in different files/packages

2021-07-17 09:42 UTC, rat6666 approved these changes

2021-07-17 11:24 UTC, merged